commercetools:
  projectKey: mach-project-2024
  clientId: bqiggycWuWT8Y8QsgCvdzAvm
  clientSecret: MvRrc9g-gL87SyNqnbiuWzM7Oo7Pq_ux
  serviceRegion: GCP_AUSTRALIA_SOUTHEAST1
management:
  endpoints:
    web:
      exposure:
        include: "*"
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html